# Generated by Django 2.1.3 on 2020-04-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatos',
            old_name='sobrenome',
            new_name='fabricante',
        ),
        migrations.RemoveField(
            model_name='contatos',
            name='email',
        ),
        migrations.AddField(
            model_name='contatos',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
