# Generated by Django 2.1.3 on 2020-04-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20200421_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='descricao',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
