# Generated by Django 2.1.3 on 2020-04-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contatos_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='descricao',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
