# Generated by Django 2.1.3 on 2020-04-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_auto_20200424_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='descricao',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
