# Generated by Django 2.1.3 on 2020-04-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0006_auto_20200427_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contatos.Contatos')),
            ],
        ),
    ]
