# Generated by Django 2.1.3 on 2020-04-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0007_listamaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listamaterial',
            name='produto',
        ),
        migrations.AddField(
            model_name='listamaterial',
            name='produto',
            field=models.ManyToManyField(blank=True, to='contatos.Contatos'),
        ),
    ]
