# Generated by Django 2.1.3 on 2020-04-27 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0008_auto_20200427_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listamaterial',
            name='produto',
        ),
        migrations.AddField(
            model_name='listamaterial',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contatos.Contatos'),
        ),
    ]
