# Generated by Django 2.1.3 on 2020-05-05 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0010_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contatos.Fornecedor'),
        ),
    ]
