# Generated by Django 2.1.3 on 2020-05-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0014_auto_20200505_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=30)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('valor', models.FloatField(default=0)),
                ('data', models.DateTimeField()),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contatos.Fornecedor')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contatos.Grupos')),
            ],
        ),
        migrations.RemoveField(
            model_name='contatos',
            name='fornecedor',
        ),
        migrations.AlterField(
            model_name='listamaterial',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contatos.Produtos'),
        ),
        migrations.DeleteModel(
            name='Contatos',
        ),
    ]
