# Generated by Django 2.1.3 on 2020-05-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0015_auto_20200507_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
