# Generated by Django 2.1.3 on 2020-08-05 16:11

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0017_auto_20200803_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
