# Generated by Django 3.1 on 2020-08-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0018_fornecedor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=100)),
                ('itens_lista', models.ManyToManyField(to='contatos.ListaMaterial')),
            ],
        ),
    ]
