# Generated by Django 3.1 on 2020-08-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0019_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='phone',
        ),
    ]
