# Generated by Django 3.1 on 2020-08-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0020_remove_fornecedor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='itens_lista',
        ),
    ]
