# Generated by Django 3.1 on 2020-08-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0021_remove_projeto_itens_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='itens_lista',
            field=models.ManyToManyField(to='contatos.ListaMaterial'),
        ),
    ]
