# Generated by Django 3.1 on 2020-09-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0022_projeto_itens_lista'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docupload', models.FileField(upload_to='documents')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
