# Generated by Django 3.1 on 2020-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0023_docfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfiles',
            name='docupload',
            field=models.FileField(upload_to='media'),
        ),
    ]
