# Generated by Django 3.1 on 2020-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0025_auto_20200904_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfiles',
            name='docupload',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
