# Generated by Django 3.1 on 2020-09-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0027_auto_20200909_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
