# Generated by Django 3.1 on 2020-09-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0031_auto_20200910_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listamaterial',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contatos.projeto'),
        ),
    ]
