# Generated by Django 3.1 on 2020-09-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0033_auto_20200911_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='margem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
