# Generated by Django 3.1 on 2020-09-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0036_auto_20200915_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='tempo_de_instalacao',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
