# Generated by Django 3.1 on 2020-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0037_produtos_tempo_de_instalacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='listamaterial',
            name='total',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
