# Generated by Django 3.1 on 2020-09-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0038_listamaterial_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listamaterial',
            name='total',
        ),
    ]
