# Generated by Django 3.1 on 2020-09-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0039_remove_listamaterial_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='valor_infra',
            field=models.IntegerField(default=40),
        ),
    ]
