# Generated by Django 3.1 on 2020-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0041_auto_20200917_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
