# Generated by Django 3.1 on 2020-09-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0043_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='valor',
            new_name='valor_de_compra',
        ),
    ]
