# Generated by Django 3.1 on 2020-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0044_auto_20200923_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='tempo_de_sup',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='produtos',
            name='valor_de_terceiros',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor_upe',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=5),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor_upi',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=5),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor_upr',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=5),
        ),
    ]
