# Generated by Django 3.1 on 2020-10-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0046_auto_20201001_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='valor_sup',
            field=models.DecimalField(decimal_places=2, default=64.0, max_digits=5),
        ),
    ]
