# Generated by Django 3.1 on 2020-10-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0047_projeto_valor_sup'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
