# Generated by Django 2.1.3 on 2020-11-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0051_docfiles_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfiles',
            name='docupload',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
