# Generated by Django 2.1.3 on 2021-02-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0053_auto_20201117_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
