# Generated by Django 2.1.3 on 2021-03-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0056_tipoprojeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo_de_projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contatos.TipoProjeto'),
        ),
    ]
