# Generated by Django 3.0.4 on 2021-03-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0057_projeto_tipo_de_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
