# Generated by Django 3.0.4 on 2021-03-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0059_auto_20210305_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(max_length=100),
        ),
    ]
