# Generated by Django 3.0.4 on 2021-03-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0061_auto_20210305_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
