# Generated by Django 2.1.3 on 2021-05-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0065_auto_20210405_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfiles',
            name='docupload',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
